# Generated by Django 3.2.3 on 2021-05-27 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='listing',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='listing_id',
        ),
    ]
